name:  测试一下 build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name:  设置 node 版本
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: 运行 build
      run: |
        npm install
        node ./scripts/build.js
